CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  affiliate_link TEXT NOT NULL,
  title TEXT NOT NULL,
  category TEXT NULL,
  price DECIMAL(12,2) NULL,
  image TEXT NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);