create table if not exists public.products (
  id bigint generated by default as identity primary key,
  affiliate_link text not null,
  title text not null,
  price numeric null,
  image text null,
  description text null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "public_can_read_products" on public.products;
create policy "public_can_read_products"
on public.products for select
to public
using (true);

drop policy if exists "authenticated_can_insert_products" on public.products;
create policy "authenticated_can_insert_products"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "authenticated_can_delete_products" on public.products;
create policy "authenticated_can_delete_products"
on public.products for delete
to authenticated
using (true);
